// src/components/WebView.tsx
import {
  type Component,
  onMount,
  createEffect,
  createMemo,
  createSignal,
} from "solid-js";
import { type Tab } from "../stores/tabs/common";
import { WebviewTag } from "electron";
import { themeStore } from "../stores/themes/solid";
import { unwrap } from "solid-js/store";

const WebView: Component<{ tab: Tab }> = (props) => {
  const { tab } = props;

  let webviewRef: WebviewTag | undefined;
  const [didStopLoading, setDidStopLoading] = createSignal(false);

  const selectedTheme = createMemo(() => {
    return unwrap(
      themeStore.themes.find((theme) => theme.id === tab.config.theme)
    );
  });

  createEffect(() => {
    if (!webviewRef) return;
    if (!didStopLoading()) return;

    webviewRef.send("set-theme", selectedTheme());
  });

  createEffect(() => {
    if (!webviewRef) return;
    if (!didStopLoading()) return;

    webviewRef.setAudioMuted(!tab.config.sound);
  });

  onMount(() => {
    const webview = webviewRef;

    if (!webview) {
      return;
    }

    webview.addEventListener("did-stop-loading", () => {
      setDidStopLoading(false);
      setDidStopLoading(true);
    });
  });

  return (
    <webview
      ref={webviewRef}
      class="w-full h-full"
      id={`webview-${tab.id}`}
      src="https://web.whatsapp.com"
      partition={`persist:${tab.id}`}
      preload={window.whatsappPreloadPath}
      webpreferences={`spellcheck=${tab.config.spellChecker}`}
    />
  );
};

export default WebView;

// src/components/WebView.svelte
<script lang="ts">
  import { afterUpdate } from "svelte";
  import type { TabType } from "../types";
  import { themes } from "../store";
  export let partition;
  export let tab: TabType;

  let webviewElement;
  let hasStoppedLoading = false;

  const sendWebviewConfig = () => {
    let currentTheme = $themes.find((theme) => theme.name === tab.config.theme);
    if (currentTheme) {
      webviewElement.send("set-theme", {
        name: tab.config.theme,
        ...(currentTheme.css
          ? {
              css: currentTheme.css,
            }
          : {}),
      });
    } else {
      webviewElement.send("set-theme", {
        name: tab.config.theme,
        css: "",
      });
    }
    webviewElement.setAudioMuted(!tab.config.sound);
  };

  afterUpdate(() => {
    if (!hasStoppedLoading) {
      webviewElement.addEventListener("did-stop-loading", () => {
        hasStoppedLoading = true;
        sendWebviewConfig();
      });
    } else {
      sendWebviewConfig();
    }
  });
</script>

<webview
  id={`webview-${partition}`}
  src="https://web.whatsapp.com"
  preload="../src/preload.js"
  {partition}
  bind:this={webviewElement}
  useragent={window.navigator.userAgent.replace(
    /(Altus4|Electron)([^\s]+\s)/g,
    ""
  )}
  webpreferences={`spellcheck=${tab.config.spellChecker ? 1 : 0}`}
/>
